import test from 'node:test';
import assert from 'node:assert/strict';
import { initialWorld } from '../shared/world.ts';
import { jevBody, parseJevResponse, parseSlowResponse, safeBaseUrl, createProviders, type Settings } from '../server/providers.ts';
const choices={drink:'喝水',consult_llm:'邀请慢思考'};
test('Jev adapter uses the documented systemone state/model/questions contract',()=>{const body=jevBody({state:initialWorld(),candidates:choices,reflectReady:false},'jev-latest');assert.equal(body.model,'jev-latest');assert.equal(body.questions.next_action.type,'choice');assert.deepEqual(body.questions.next_action.criteria,choices);assert.equal(Object.keys(body.questions).length,1)});
test('strict Choice parsing validates chosen ID, full distribution, ranges and sum',()=>{const answer={type:'choice',choice:'drink',probabilities:{drink:.8,consult_llm:.2},confidence:.62};assert.equal(parseJevResponse({answers:{next_action:answer}},choices).choice,'drink');for(const invalid of [{...answer,choice:'sleep'},{...answer,probabilities:{drink:.8}},{...answer,probabilities:{drink:.8,consult_llm:.8}},{...answer,confidence:2}])assert.throws(()=>parseJevResponse({answers:{next_action:invalid}},choices))});
test('LLM response is parsed as advisory data with grounded source IDs only',()=>{const s=initialWorld();s.messages.push({id:'u1',role:'user',text:'喜欢安静',source:'user',at:1});const raw={choices:[{message:{content:JSON.stringify({summary:'建议',reply:'明白',suggestions:['drink','delete_all_files'],memories:[{text:'喜欢安静',sourceMessageId:'u1'},{text:'未提供的属性',sourceMessageId:'fake'}]})}}]};const parsed=parseSlowResponse(raw,s);assert.deepEqual(parsed.suggestions,['drink']);assert.equal(parsed.memories.length,1);assert.throws(()=>parseSlowResponse({choices:[{message:{content:'not JSON'}}]},s))});
test('custom endpoints reject credential-bearing URLs and remote plain HTTP',()=>{assert.equal(safeBaseUrl('http://localhost:11434/v1/'),'http://localhost:11434/v1');assert.equal(safeBaseUrl('https://example.com/v1'),'https://example.com/v1');for(const bad of ['http://example.com/v1','https://user:pass@example.com/v1','https://example.com/v1?key=x','file:///etc/passwd'])assert.throws(()=>safeBaseUrl(bad))});
test('live request targets the official API, keeps keys out of the body and surfaces HTTP failures',async()=>{
  const original=globalThis.fetch;let url='',body='',authorization='';
  globalThis.fetch=async(input,init)=>{url=String(input);body=String(init?.body);authorization=new Headers(init?.headers).get('Authorization')||'';return new Response('{}',{status:529})};
  try{const config:Settings={mode:'live',jevKey:'test-only-secret',jevModel:'jev-latest',llmKey:'',llmModel:'',llmBaseUrl:'https://example.com/v1'};const p=createProviders(()=>config);await assert.rejects(p.fast({state:initialWorld('live'),candidates:choices,reflectReady:false},new AbortController().signal),/529/);assert.equal(url,'https://api.typesafe.ai/v1/systemone');assert.equal(authorization,'Bearer test-only-secret');assert.ok(!body.includes('test-only-secret'));assert.equal(p.slowReady(),false)}finally{globalThis.fetch=original}
});
