import test from 'node:test';
import assert from 'node:assert/strict';
import { AgentRuntime } from '../server/runtime.ts';
import { demoChoice, type Providers, type FastResult, type SlowResult } from '../server/providers.ts';
import { OBJECTS, findPath, isWalkable, type DecisionId } from '../shared/world.ts';
const fast=(choice:DecisionId):FastResult=>({choice,probabilities:{[choice]:1},confidence:1,latency:1});
const slow:SlowResult={summary:'Only advice',reply:'建议先休息。',suggestions:['sleep'],memories:[],latency:1};
const flush=()=>new Promise<void>(r=>setTimeout(r,0));
function fixture(){let choice:DecisionId='continue',slowCalls=0;const providers:Providers={fast:async()=>fast(choice),slow:async()=>{slowCalls++;return slow},slowReady:()=>true};const runtime=new AgentRuntime(providers);return {runtime,providers,set:(c:DecisionId)=>choice=c,get slowCalls(){return slowCalls}}}
function finish(runtime:AgentRuntime){for(let i=0;i<1600&&runtime.state.agent.action;i++)runtime.step(.1);assert.equal(runtime.state.agent.action,null,'action must complete with valid navigation')}

test('all 12 interaction points are walkable and connected without crossing furniture or walls',()=>{
  for(const a of OBJECTS){assert.ok(isWalkable(a.approach),a.id);for(const b of OBJECTS){const path=findPath(a.approach,b.approach);assert.ok(path,`${a.id} -> ${b.id}`);assert.ok(path.every(isWalkable));}}
});
test('chat cannot execute a behavior before the fast system makes its choice',async()=>{const f=fixture();f.runtime.chat('去睡觉');assert.equal(f.runtime.state.agent.action,null);assert.equal(f.slowCalls,0);f.set('drink');await f.runtime.decide();assert.equal(f.runtime.snapshot().agent.action?.id,'drink');assert.equal(f.slowCalls,0);f.runtime.dispose()});
test('LLM is only invited by a fast decision; suggestions never auto-execute',async()=>{const f=fixture();f.runtime.chat('帮我规划今天');await f.runtime.decide();assert.equal(f.slowCalls,0);f.set('consult_llm');await f.runtime.decide();await flush();assert.equal(f.slowCalls,1);assert.equal(f.runtime.state.agent.action,null);assert.deepEqual(f.runtime.state.advice?.suggestions,['sleep']);f.set('read');await f.runtime.decide();assert.equal(f.runtime.snapshot().agent.action?.id,'read');f.runtime.dispose()});
test('a new user message invalidates an older in-flight fast answer',async()=>{const f=fixture();let resolve!:(v:FastResult)=>void;f.providers.fast=()=>new Promise(r=>resolve=r);f.runtime.chat('喝水');const pending=f.runtime.decide();f.runtime.chat('去睡觉');resolve(fast('drink'));await pending;assert.equal(f.runtime.state.agent.action,null);assert.equal(f.runtime.state.request?.text,'去睡觉');f.runtime.dispose()});
test('pause invalidates pending decisions and freezes simulation time',async()=>{const f=fixture();let resolve!:(v:FastResult)=>void;f.providers.fast=()=>new Promise(r=>resolve=r);const pending=f.runtime.decide();f.runtime.control('pause');const clock=f.runtime.state.clock;f.runtime.step(1);resolve(fast('work'));await pending;assert.equal(f.runtime.state.clock,clock);assert.equal(f.runtime.state.agent.action,null);f.runtime.dispose()});
test('old slow suggestions and memories cannot overwrite a new user request',async()=>{const f=fixture();let resolve!:(v:SlowResult)=>void;f.providers.slow=()=>new Promise(r=>resolve=r);const id=f.runtime.chat('记住我喜欢安静');f.set('reflect_memory');await f.runtime.decide();f.runtime.chat('取消，先喝水');resolve({...slow,memories:[{text:'old',sourceMessageId:id}]});await flush();assert.equal(f.runtime.state.memories.length,0);assert.equal(f.runtime.state.advice,null);f.runtime.dispose()});
test('only valid memory evidence is saved, and resetting preserves memories',async()=>{let saved=0;let id='';const providers:Providers={fast:async()=>fast('reflect_memory'),slow:async()=>({...slow,memories:[{text:'喜欢安静',sourceMessageId:id},{text:'invented',sourceMessageId:'missing'}]}),slowReady:()=>true};const r=new AgentRuntime(providers,'demo',mem=>saved=mem.length);id=r.chat('记住我喜欢安静');await r.decide();await flush();assert.equal(saved,1);assert.equal(r.state.memories.length,1);r.control('reset');assert.equal(r.state.memories.length,1);r.dispose()});
test('offline demo completes an ordered request through independent fast decisions',async()=>{const providers:Providers={fast:async input=>fast(demoChoice(input)),slow:async()=>slow,slowReady:()=>true};const r=new AgentRuntime(providers);r.chat('先喝水，再读书');await r.decide();assert.equal(r.state.agent.action?.id,'drink');finish(r);assert.deepEqual(r.state.request?.completed,['drink']);await r.decide();assert.equal(r.state.agent.action?.id,'read');finish(r);await r.decide();assert.equal(r.state.request?.status,'done');assert.deepEqual(r.state.request?.completed,['drink','read']);r.dispose()});
test('resource effects are committed once and only after arrival and interaction',async()=>{const f=fixture();f.set('cook');const food=f.runtime.state.resources.food;await f.runtime.decide();assert.equal(f.runtime.state.resources.food,food);finish(f.runtime);assert.equal(f.runtime.state.resources.food,food-1);assert.equal(f.runtime.state.resources.meals,1);f.runtime.step(1);assert.equal(f.runtime.state.resources.meals,1);f.runtime.dispose()});
test('invalid choices never execute, and live failures never invoke the simulator',async()=>{const f=fixture();f.runtime.configure('live');f.runtime.state.resources.food=0;f.set('cook');await f.runtime.decide();assert.equal(f.runtime.state.agent.action,null);assert.equal(f.runtime.state.fast.status,'error');assert.equal(f.runtime.state.mode,'live');assert.ok(!f.runtime.state.traces.some(t=>t.title==='本地规则选择'));f.runtime.dispose()});
test('new commands can interrupt a previously chosen action without applying its effects',async()=>{const f=fixture();f.set('sleep');await f.runtime.decide();const energy=f.runtime.state.agent.needs.energy;f.runtime.chat('不要睡觉，先喝水');f.set('drink');await f.runtime.decide();assert.equal(f.runtime.snapshot().agent.action?.id,'drink');assert.equal(f.runtime.state.agent.needs.energy,energy);f.runtime.dispose()});
test('a continued action is attributed to the latest request only after the fast choice',async()=>{const f=fixture();f.set('drink');await f.runtime.decide();f.runtime.chat('继续喝水');assert.equal(f.runtime.state.agent.action?.requestId,null);f.set('continue');await f.runtime.decide();finish(f.runtime);assert.deepEqual(f.runtime.state.request?.completed,['drink']);f.runtime.dispose()});
test('switching model mode resets metrics instead of presenting simulated latency as live',async()=>{const f=fixture();f.set('drink');await f.runtime.decide();assert.equal(f.runtime.state.fast.calls,1);f.runtime.configure('live');assert.equal(f.runtime.state.fast.calls,0);assert.equal(f.runtime.state.fast.lastLatency,null);assert.equal(f.runtime.state.slow.calls,0);f.runtime.dispose()});
