import './style.css';
import { HomeScene } from './scene.ts';
import { ACTIONS, OBJECTS, type WorldObject, type WorldState } from '../shared/world.ts';
const paths:Record<string,string>={cube:'m12 3 9 5v8l-9 5-9-5V8zm0 9 9-4m-9 4L3 8m9 4v9',settings:'M4 7h16M4 17h16M8 4v6m8 4v6',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5zm7-2v4m-2-2h4',brain:'M12 19V5m0 1C8 1 4 5 6 8c-5 1-4 7 0 7-1 5 5 6 6 3m0-12c4-5 8-1 6 2 5 1 4 7 0 7 1 5-5 6-6 3M7 9l3 2m7-2-3 2M7 15l3-2m7 2-3-2',bolt:'m13 2-9 12h7l-1 8 10-13h-8z',chat:'M20 11a8 8 0 0 1-8 8H5l-3 3v-7a8 8 0 1 1 18-4',book:'M12 6v15M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-3-1-6 0-9 2-3-2-6-3-9-2z',arrow:'M12 20V4m-6 6 6-6 6 6',chevron:'m9 5 7 7-7 7',drop:'M12 3c-3 5-7 8-7 12a7 7 0 0 0 14 0c0-4-4-7-7-12z',leaf:'M4 20 19 5M4 15C1 3 14 3 21 3c0 9-1 18-12 15',heart:'M20 5c-3-3-6-1-8 1-2-2-5-4-8-1-5 5 3 12 8 16 5-4 13-11 8-16z',food:'M5 3v7m4-7v7M3 3v5c0 5 8 5 8 0V3M7 12v9M19 3c-5 3-5 11 0 11m0-11v18',sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1M16 12a4 4 0 1 0-8 0 4 4 0 0 0 8 0',reset:'M3 11a9 9 0 1 1 2 7M3 3v8h8',pause:'M8 5v14M16 5v14',play:'m7 4 13 8-13 8z',plus:'M12 4v16M4 12h16',minus:'M4 12h16',focus:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',close:'m6 6 12 12M6 18 18 6',mic:'M9 5a3 3 0 0 1 6 0v8a3 3 0 0 1-6 0zm-3 6v2a6 6 0 0 0 12 0v-2M12 19v3m-3 0h6',mute:'m11 4-6 5H2v6h3l6 5zm5 5 6 6m-6 0 6-6',sound:'m11 4-6 5H2v6h3l6 5zm4 4c3 2 3 6 0 8m3-11c5 4 5 10 0 14',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',grid:'M3 3h6v6H3zm12 0h6v6h-6zM3 15h6v6H3zm12 0h6v6h-6z',check:'m4 12 5 5L20 6',history:'M4 4v6h6M4 10a8 8 0 1 1 1 7m7-10v5l3 2'};
const icon=(id:string,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[id]||paths.spark}"/></svg>`;
const robot=`<svg viewBox="0 0 48 48" fill="none" aria-hidden="true"><path d="M24 5v6" stroke="#c4ad7f" stroke-width="3"/><circle cx="24" cy="4" r="2.5" fill="#d1b882"/><rect x="7" y="12" width="34" height="28" rx="10" fill="#b8cfa9"/><rect x="11" y="17" width="26" height="18" rx="6" fill="#456852"/><rect x="17" y="23" width="3" height="6" rx="1.5" fill="#edf1d7"/><rect x="28" y="23" width="3" height="6" rx="1.5" fill="#edf1d7"/></svg>`;
const escape=(text:unknown)=>String(text??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]!));
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const time=(at:number)=>new Date(at).toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit'});
let state:WorldState|null=null,token='',connected=false,tab='chat',messageKey='',memoryKey='',traceKey='',selected:WorldObject|null=null,voiceOn=false,seenMessages=new Set<string>();
interface Config {mode:'demo'|'live';jevModel:string;hasJevKey:boolean;llmBaseUrl:string;llmModel:string;hasLlmKey:boolean;llmReady:boolean}
let config:Config={mode:'demo',jevModel:'jev-latest',hasJevKey:false,llmBaseUrl:'https://api.openai.com/v1',llmModel:'',hasLlmKey:false,llmReady:false};
$('app').innerHTML=`
<header class="topbar"><a class="brand" href="/" aria-label="RealtimeAgent 首页"><span class="brand-mark">${icon('cube')}</span><span><strong>Realtime<span>Agent</span></strong><small>EXPERIMENT 001</small></span></a><p class="tagline"><i></i>A little world. A living mind.</p><div class="header-tools"><span class="connection" id="connection"><i></i>连接中</span><span class="mode-pill" id="mode-pill">OFFLINE DEMO</span><button class="outline" id="settings-open">${icon('settings')}<span>模型连接</span></button></div></header>
<div class="layout"><main class="playground"><div class="section-heading"><div><span class="eyebrow">THE PLAYGROUND</span><h1>让智能，生活起来<span>。</span></h1></div><button class="text-button" id="objects-open">${icon('grid')} <span>${OBJECTS.length} 个交互对象</span>${icon('chevron')}</button></div>
<section class="world-card" aria-label="实时三维家园"><div class="world-heading"><span>MILO’S LITTLE WORLD <em>01</em></span><span class="world-time">${icon('sun')}<b id="world-clock">09:30</b><span>晴朗的一天</span></span></div><div class="mode-note" id="mode-note">本地规则模拟 · 未调用 Jev / LLM</div><div id="world"></div><div class="object-popover" id="object-popover" hidden></div><div class="agent-card"><div class="mini-avatar">${robot}</div><div class="agent-card-main"><div><strong>Milo</strong><span id="action-phase">等待中</span></div><p id="action-name">正在连接小世界</p><div class="action-progress"><i id="action-progress"></i></div></div><i class="live-dot"></i></div><span class="scene-hint">拖动旋转 · 滚轮缩放 · 点击物体</span><div class="camera-tools"><button id="camera-reset" aria-label="重置视角">${icon('focus')}</button><span></span><button id="zoom-in" aria-label="放大">${icon('plus')}</button><button id="zoom-out" aria-label="缩小">${icon('minus')}</button></div></section>
<div class="world-toolbar"><div><button class="icon-button tinted" id="pause" aria-label="暂停世界">${icon('pause')}</button><span id="run-label">实时运行</span><span class="separator"></span><button id="speed1" class="speed active">1×</button><button id="speed3" class="speed">3×</button><span class="separator"></span><button class="icon-button" id="reset" aria-label="重置世界">${icon('reset')}</button></div><div class="resources"><span>${icon('food')}<b id="food-count">6</b> 份食材</span><button class="text-button" id="restock" title="用户改变环境，不直接决定 Agent 行动">补充 ${icon('plus')}</button><span class="separator"></span><span>${icon('leaf')}<b id="plant-water">48</b>%</span></div></div>
<section class="runtime-panel"><div class="runtime-heading"><h2>${icon('brain')} 双系统运行时</h2><button class="text-button" id="trace-open">查看决策记录 ${icon('chevron')}</button></div><div class="system-flow"><article class="system fast" id="fast-card"><div class="system-icon">${icon('bolt')}</div><div class="system-name"><h3>Jev <span>SYSTEM 1</span></h3><p id="fast-subtitle">此刻，应该做什么？</p></div><i class="status-dot" id="fast-dot"></i><div class="system-bottom"><span id="fast-status">本地规则模拟</span><span id="fast-metric">SIMULATED</span></div></article><div class="flow-arrows"><span>⟶</span><small>按需思考</small><span>⟵</span></div><article class="system slow" id="slow-card"><div class="system-icon">${icon('brain')}</div><div class="system-name"><h3>LLM <span>SYSTEM 2</span></h3><p>慢一点，想得更远。</p></div><i class="status-dot" id="slow-dot"></i><div class="system-bottom"><span id="slow-status">等待被邀请</span><span id="slow-metric">0 次模拟</span></div></article></div><div class="runtime-footer"><span id="last-decision">最终动作由快系统选择；LLM 不能直接执行</span><span id="decision-count">0 次选择</span></div><p class="runtime-error" id="runtime-error" hidden></p></section><footer class="playground-footer"><span><i></i>LOCAL SIMULATION</span><em>Every action has a decision behind it.</em><button class="text-button" id="export">${icon('download')} 导出记录</button></footer></main>
<aside class="sidebar"><div class="profile"><div class="avatar">${robot}<i></i></div><div class="profile-name"><h2>Milo <span>你的生活 Agent</span></h2><p><i></i><span id="profile-activity">等待世界醒来</span></p></div><button class="icon-button" id="voice-toggle" aria-label="开启语音播报" title="开启浏览器语音播报">${icon('mute')}</button></div><div class="needs">${([['food','food','饱腹'],['water','drop','水分'],['energy','bolt','精力'],['mood','heart','心情'],['clean','spark','清洁']] as string[][]).map(([key,ico,label])=>`<div class="need ${key}"><div>${icon(ico)}<b id="need-${key}">—</b></div><div class="need-track"><i id="bar-${key}"></i></div><small>${label}</small></div>`).join('')}</div><nav class="tabs" aria-label="Agent 面板"><button class="tab active" data-tab="chat">${icon('chat')} 实时对话</button><button class="tab" data-tab="memory">${icon('book')} 长期记忆 <em id="memory-count">0</em></button><button class="tab" data-tab="trace" aria-label="决策记录">${icon('history')}</button></nav><div class="conversation" id="chat-panel"><div class="day-separator"><span></span>今天 · 小世界的一天<span></span></div><div id="messages" aria-live="polite" aria-relevant="additions"></div><div id="thinking-message" hidden><i></i><span>慢系统正在思考，世界仍在运行…</span></div></div><div class="memory-panel scroll-panel" id="memory-panel" hidden></div><div class="trace-panel scroll-panel" id="trace-panel" hidden></div>
<div class="composer-wrap"><small class="prompt-heading">从一句话开始</small><div class="suggestions"><button data-prompt="先喝水，再读书。">${icon('drop')}先喝水，再读书</button><button data-prompt="给花园浇水。">${icon('leaf')}给花园浇水</button><button data-prompt="记住：我喜欢安静，工作后先休息。">${icon('spark')}记住一个偏好</button></div><form class="composer" id="chat-form"><textarea id="message-input" aria-label="和 Milo 说点什么" placeholder="和 Milo 说点什么…" maxlength="2000" rows="2"></textarea><div><span><button type="button" class="icon-button" id="mic" aria-label="语音输入">${icon('mic')}</button><small id="input-hint">Enter 发送 · Shift + Enter 换行</small></span><button class="send" type="submit" id="send" aria-label="发送消息">${icon('arrow')}</button></div></form><p class="composer-note">${icon('spark')} 聊天随时打断，世界因你的一句话而改变。<br><span>动作播报为模板；自由回复按需由 LLM 生成。</span></p></div></aside></div>
<dialog id="settings-dialog"><div class="dialog-heading"><div><span class="eyebrow">CONNECT THE MIND</span><h2>连接两个思考系统</h2></div><button class="icon-button dialog-close" aria-label="关闭">${icon('close')}</button></div><p class="dialog-intro">Jev 决定每一步行动，也决定何时邀请 LLM。密钥仅保留在本地服务进程，不保存到浏览器。</p><form id="settings-form"><div class="mode-options"><label><input type="radio" name="mode" value="demo" checked/><strong>本地流程演示</strong><small>规则模拟 · 不调用模型</small></label><label><input type="radio" name="mode" value="live"/><strong>连接真实模型</strong><small>真实 Jev 决策 · 按需 LLM</small></label></div><fieldset><legend>${icon('bolt')} Jev · 快系统</legend><label>TypeSafe API Key <input id="jev-key" type="password" autocomplete="off" placeholder="留空保留已有密钥"/></label><label>模型名称 <input id="jev-model" value="jev-latest" required/></label><small id="jev-key-status">未配置密钥</small></fieldset><fieldset><legend>${icon('brain')} LLM · 慢系统</legend><label>API Base URL <input id="llm-url" type="url" value="https://api.openai.com/v1" required/></label><div class="field-row"><label>模型 ID <input id="llm-model" placeholder="填写提供商的模型 ID"/></label><label>API Key <input id="llm-key" type="password" autocomplete="off" placeholder="留空保留已有密钥"/></label></div><small id="llm-key-status">兼容 /chat/completions；未配置时不会调用 LLM</small></fieldset><p class="privacy-note">开启真实模式后，家园状态、近期对话与相关记忆会发送给所配置的模型提供商。此 Demo 仅监听本机地址，不应直接暴露到公网。</p><div class="dialog-actions"><button type="button" class="text-button" id="clear-keys">断开模型并清除会话密钥</button><button class="primary" type="submit" id="save-settings">保存连接 ${icon('arrow')}</button></div></form></dialog>
<dialog id="objects-dialog"><div class="dialog-heading"><div><span class="eyebrow">LITTLE THINGS, REAL ACTIONS</span><h2>家里的每一件小事</h2></div><button class="icon-button dialog-close" aria-label="关闭">${icon('close')}</button></div><p class="dialog-intro">点击物体发送生活指令。是否执行、何时执行，仍由快系统决定。</p><div class="object-grid">${OBJECTS.map(o=>`<button data-object="${o.id}"><span style="--object-color:${o.color}">${icon(o.id==='bookshelf'?'book':o.id==='planter'?'leaf':'cube')}</span><strong>${o.name}</strong><small>${o.room} · ${ACTIONS[o.actions[0]].label}</small>${icon('chevron')}</button>`).join('')}</div></dialog><div id="toast" role="status"></div>`;
let scene:HomeScene|null=null;
try{scene=new HomeScene($('world'),showObject)}catch{$('world').innerHTML='<div class="webgl-error"><strong>浏览器暂时无法启动 3D 渲染</strong><p>请启用硬件加速；仍可通过上方「交互对象」和聊天操作家园。</p></div>'}
function toast(message:string){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),4500)}
function showObject(object:WorldObject){selected=object;const p=$('object-popover');p.hidden=false;p.innerHTML=`<div><span class="eyebrow">${escape(object.room)}</span><button class="icon-button" id="object-close" aria-label="关闭物体信息">${icon('close')}</button></div><h3>${escape(object.name)}</h3><p>交互会作为指令交给快系统。</p>${object.actions.map(id=>`<button class="object-action" data-action="${id}">${escape(ACTIONS[id].label)} ${icon('arrow')}</button>`).join('')}`;scene?.setSelected(object.id);$('object-close').onclick=()=>{p.hidden=true;scene?.setSelected(null);selected=null};p.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>{void sendMessage(`请${ACTIONS[b.dataset.action as keyof typeof ACTIONS].label}。`);p.hidden=true;scene?.setSelected(null)})}
async function post(path:string,data:unknown){if(!token||!connected)throw new Error('本地服务尚未连接，请等待连接恢复');const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-RA-Token':token},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error||'请求失败');return result}
async function sendMessage(text:string){if(!text.trim())return;const send=$<HTMLButtonElement>('send');if(send.disabled)return;send.disabled=true;try{await post('/api/chat',{text});setTab('chat');if($<HTMLTextAreaElement>('message-input').value.trim()===text.trim())$<HTMLTextAreaElement>('message-input').value=''}catch(err){toast((err as Error).message)}finally{send.disabled=false}}
async function control(action:string,value?:number){try{await post('/api/control',{action,value})}catch(err){toast((err as Error).message)}}
function setTab(next:string){tab=next;document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('chat-panel').hidden=tab!=='chat';$('memory-panel').hidden=tab!=='memory';$('trace-panel').hidden=tab!=='trace'}
function render(s:WorldState){state=s;scene?.update(s);const demo=s.mode==='demo',a=s.agent.action;
  $('world-clock').textContent=`${String(Math.floor(s.clock/60)).padStart(2,'0')}:${String(Math.floor(s.clock%60)).padStart(2,'0')}`;
  document.querySelector('.playground-footer>span')!.innerHTML='<i></i>'+(demo?'LOCAL SIMULATION':'LIVE MODEL MODE');$('mode-pill').textContent=demo?'OFFLINE DEMO':'LIVE · JEV';$('mode-pill').classList.toggle('live',!demo);$('mode-note').textContent=demo?'本地规则模拟 · 未调用 Jev / LLM':'真实 Jev 决策 · LLM 仅按需调用';
  const activity=a?ACTIONS[a.id].doing:s.paused?'世界已暂停':s.fast.status==='thinking'?'正在选择下一步':'观察小世界';$('action-name').textContent=activity;$('profile-activity').textContent=activity;$('action-phase').textContent=s.paused?'已暂停':a?.phase==='walking'?'走过去':a?'互动中':'等待中';$('action-progress').style.width=`${a?.phase==='acting'?a.progress*100:a?18:0}%`;
  for(const [key,value]of Object.entries(s.agent.needs)){$(`need-${key}`).textContent=String(Math.round(value));$(`bar-${key}`).style.width=`${value}%`}
  $('pause').innerHTML=icon(s.paused?'play':'pause');$('pause').setAttribute('aria-label',s.paused?'继续世界':'暂停世界');$('run-label').textContent=s.paused?'已暂停':'实时运行';$('speed1').classList.toggle('active',s.speed===1);$('speed3').classList.toggle('active',s.speed===3);$('food-count').textContent=String(s.resources.food);$('plant-water').textContent=String(Math.round(s.resources.plantWater));
  const fastBusy=s.fast.status==='thinking',slowBusy=s.slow.status==='thinking';$('fast-card').classList.toggle('busy',fastBusy);$('slow-card').classList.toggle('busy',slowBusy);
  $('fast-status').textContent=s.fast.status==='error'?'连接异常 · 不执行新决策':fastBusy?demo?'模拟器选择中':'Jev 决策中':demo?'本地规则模拟':s.fast.lastLatency===null?'等待真实 Jev 返回':'真实 Jev · 已返回决策';
  $('fast-metric').textContent=s.fast.lastLatency===null?(demo?'SIMULATED':'READY'):`${s.fast.lastLatency} ms${demo?' · 模拟':''}`;
  $('slow-status').textContent=slowBusy?'被 Jev 邀请，正在思考':s.slow.status==='error'?'慢思考失败':!demo&&!config.llmReady?'尚未配置模型':'等待被邀请';$('slow-metric').textContent=`${s.slow.calls} 次${demo?'模拟':'调用'}`;
  const choice=ACTIONS[s.fast.lastChoice as keyof typeof ACTIONS]?.label||({continue:'继续当前动作',stop:'停止并等待',finish_request:'当前请求完成',consult_llm:'邀请 LLM 慢思考',reflect_memory:'邀请 LLM 整理记忆'} as Record<string,string>)[s.fast.lastChoice]||s.fast.lastChoice;
  $('last-decision').textContent=`最近选择：${choice}`;$('decision-count').textContent=`${s.fast.calls} 次${demo?'模拟选择':'Jev 调用'}`;
  const error=s.fast.error||s.slow.error;$('runtime-error').hidden=!error;$('runtime-error').textContent=error||'';
  const mk=s.messages.map(m=>m.id).join('|');if(mk!==messageKey){const feed=$('chat-panel'),atBottom=feed.scrollHeight-feed.scrollTop-feed.clientHeight<100;messageKey=mk;
    $('messages').innerHTML=s.messages.map(m=>`<article class="message ${m.role}" data-message-id="${m.id}"><div class="message-meta"><strong>${m.role==='user'?'你':m.role==='system'?'运行时':'Milo'}</strong><span>${escape(m.source)}</span></div><div class="message-bubble">${escape(m.text)}</div><time>${time(m.at)}</time></article>`).join('');if(atBottom)requestAnimationFrame(()=>feed.scrollTop=feed.scrollHeight);
    for(const m of s.messages){if(!seenMessages.has(m.id)&&voiceOn&&m.role==='agent'){const u=new SpeechSynthesisUtterance(m.text);u.lang='zh-CN';u.rate=1.06;window.speechSynthesis?.speak(u)}}seenMessages=new Set(s.messages.map(m=>m.id));
  }
  $('thinking-message').hidden=!slowBusy;$('memory-count').textContent=String(s.memories.length);
  const memKey=s.memories.map(m=>m.id).join('|');if(memKey!==memoryKey||!$('memory-panel').innerHTML){memoryKey=memKey;$('memory-panel').innerHTML=s.memories.length?`<div class="panel-caption">${icon('book')} ${demo?'模拟记忆，与真实模式隔离':'来自 LLM 的带来源记忆'}<small>外部记忆库，不是模型权重训练。</small></div>${s.memories.slice().reverse().map(m=>`<article class="memory-item"><span class="memory-dot"></span><p>${escape(m.text)}</p><small>${time(m.at)} · 来源 ${escape(m.sourceMessageId.slice(0,8))}</small></article>`).join('')}`:`<div class="empty-state">${icon('book')}<h3>记忆，从一段对话开始。</h3><p>告诉 Milo 一个偏好。只有快系统选择沉淀后，慢系统才会整理记忆。</p><small>模拟与真实记忆分别保存在本地。</small></div>`}
  const tk=s.traces.at(-1)?.id;if(tk&&tk!==traceKey){traceKey=tk;$('trace-panel').innerHTML=`<div class="panel-caption">${icon('history')} 行为从哪里来<small>这里只展示决策结果与建议摘要，不是模型内部思维链。概率分布≠行动成功率。</small></div>${s.traces.slice(-50).reverse().map(t=>`<article class="trace-item ${t.kind}"><div><b>${escape(t.title)}</b><time>${time(t.at)}</time></div><p>${escape(t.detail)}</p>${t.probabilities?`<div class="probabilities">${Object.entries(t.probabilities).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([key,v])=>`<div><span>${escape(key)}</span><i style="--p:${v*100}%"></i><b>${(v*100).toFixed(1)}%</b></div>`).join('')}</div>`:''}<small>${t.mode==='demo'?'模拟':'真实运行'}${t.latency!==undefined?` · ${t.latency} ms`:''}${t.choice?` · ${escape(t.choice)}`:''}</small></article>`).join('')}`}
}
$('chat-form').addEventListener('submit',e=>{e.preventDefault();void sendMessage($<HTMLTextAreaElement>('message-input').value)});
$('message-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();void sendMessage($<HTMLTextAreaElement>('message-input').value)}});
document.querySelectorAll<HTMLButtonElement>('[data-prompt]').forEach(b=>b.onclick=()=>void sendMessage(b.dataset.prompt!));document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab!));$('trace-open').onclick=()=>setTab('trace');
$('pause').onclick=()=>void control(state?.paused?'resume':'pause');$('speed1').onclick=()=>void control('speed',1);$('speed3').onclick=()=>void control('speed',3);$('restock').onclick=()=>void control('restock');$('reset').onclick=()=>{if(confirm('重置家园、当前对话和决策记录？长期记忆会保留。'))void control('reset')};
$('camera-reset').onclick=()=>scene?.resetCamera();$('zoom-in').onclick=()=>scene?.zoom(.15);$('zoom-out').onclick=()=>scene?.zoom(-.15);
$('objects-open').onclick=()=>$<HTMLDialogElement>('objects-dialog').showModal();document.querySelectorAll<HTMLButtonElement>('[data-object]').forEach(b=>b.onclick=()=>{$<HTMLDialogElement>('objects-dialog').close();showObject(OBJECTS.find(o=>o.id===b.dataset.object)!)});
document.querySelectorAll<HTMLButtonElement>('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog')?.close());document.querySelectorAll<HTMLDialogElement>('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
function populateSettings(){const radio=document.querySelector<HTMLInputElement>(`input[name="mode"][value="${config.mode}"]`);if(radio)radio.checked=true;$<HTMLInputElement>('jev-model').value=config.jevModel;$<HTMLInputElement>('llm-url').value=config.llmBaseUrl;$<HTMLInputElement>('llm-model').value=config.llmModel;$<HTMLInputElement>('jev-key').value='';$<HTMLInputElement>('llm-key').value='';$('jev-key-status').textContent=config.hasJevKey?'密钥已配置；留空保留。保存配置不代表真实请求已验证。':'未配置密钥';$('llm-key-status').textContent=config.hasLlmKey?'密钥已配置；仅在 Jev 选择调用时使用。':'兼容 /chat/completions；未配置时不会调用 LLM'}
$('settings-open').onclick=()=>{populateSettings();$<HTMLDialogElement>('settings-dialog').showModal()};
async function saveSettings(clearKeys=false){const payload={mode:clearKeys?'demo':document.querySelector<HTMLInputElement>('input[name="mode"]:checked')!.value,jevModel:$<HTMLInputElement>('jev-model').value,jevKey:$<HTMLInputElement>('jev-key').value,llmKey:$<HTMLInputElement>('llm-key').value,llmBaseUrl:$<HTMLInputElement>('llm-url').value,llmModel:$<HTMLInputElement>('llm-model').value,clearKeys};const button=$<HTMLButtonElement>('save-settings');button.disabled=true;try{config=await post('/api/settings',payload);populateSettings();$<HTMLDialogElement>('settings-dialog').close();toast(clearKeys?'会话密钥已清除，切回本地模拟':'配置已保存；连接结果会显示在运行时面板')}catch(err){toast((err as Error).message)}finally{button.disabled=false}}
$('settings-form').addEventListener('submit',e=>{e.preventDefault();void saveSettings()});$('clear-keys').onclick=()=>void saveSettings(true);
$('export').onclick=()=>{if(!state)return;const blob=new Blob([JSON.stringify({app:'RealtimeAgent',version:'0.1.0',exportedAt:new Date().toISOString(),notice:'Contains local conversation and memory; no provider keys.',state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`realtime-agent-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('voice-toggle').onclick=()=>{if(!('speechSynthesis'in window)){toast('当前浏览器不支持语音播报');return}voiceOn=!voiceOn;$('voice-toggle').innerHTML=icon(voiceOn?'sound':'mute');$('voice-toggle').setAttribute('aria-label',voiceOn?'关闭语音播报':'开启语音播报');if(!voiceOn)window.speechSynthesis.cancel();toast(voiceOn?'已开启：后续回复将由浏览器朗读':'已关闭语音播报')};
interface RecognitionEvent { results:{[index:number]:{isFinal:boolean;[index:number]:{transcript:string}};length:number};resultIndex:number }
interface Recognition {lang:string;interimResults:boolean;continuous:boolean;onresult:((e:RecognitionEvent)=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start():void;stop():void}
const speechWindow=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const RecognitionClass=speechWindow.SpeechRecognition||speechWindow.webkitSpeechRecognition;let recognition:Recognition|null=null,listening=false;
if(!RecognitionClass){$<HTMLButtonElement>('mic').disabled=true;$('mic').title='当前浏览器不支持语音识别；请使用文字输入'}
$('mic').onclick=()=>{if(!RecognitionClass)return;if(listening){recognition?.stop();return}try{window.speechSynthesis?.cancel();recognition=new RecognitionClass();recognition.lang='zh-CN';recognition.interimResults=true;recognition.continuous=false;recognition.onresult=e=>{let text='';let final=false;for(let i=0;i<e.results.length;i++){text+=e.results[i][0].transcript;final ||= e.results[i].isFinal}$<HTMLTextAreaElement>('message-input').value=text;if(final){recognition?.stop();void sendMessage(text)}};recognition.onerror=()=>toast('语音识别不可用或麦克风未授权，请使用文字输入');recognition.onend=()=>{listening=false;$('mic').classList.remove('listening');$('input-hint').textContent='Enter 发送 · Shift + Enter 换行'};recognition.start();listening=true;$('mic').classList.add('listening');$('input-hint').textContent='聆听中 · 浏览器语音识别';toast('语音由浏览器识别，可能使用其在线服务。')}catch{toast('麦克风启动失败，请使用文字输入')}};
function connectionStatus(ok:boolean){connected=ok;$('connection').innerHTML=`<i></i>${ok?'本地已连接':'正在重连'}`;$('connection').classList.toggle('offline',!ok)}
async function connect(){try{const res=await fetch('/api/bootstrap');if(!res.ok)throw new Error();const data=await res.json();token=data.token;config=data.settings;seenMessages=new Set(data.state.messages.map((m:{id:string})=>m.id));connectionStatus(true);render(data.state);const events=new EventSource('/api/events');events.addEventListener('state',e=>{connectionStatus(true);render(JSON.parse((e as MessageEvent).data))});events.onerror=()=>connectionStatus(false)}catch{connectionStatus(false);setTimeout(connect,2500)}}
void connect();
